In [3]:
import numpy as np

In [4]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [7]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [8]:
A = np.random.randn(10)

In [9]:
A

array([ 0.48736733,  0.92225484,  0.36486967, -0.67269136, -0.16766685,
        0.05864259, -0.73393265,  1.26125482, -1.43380242, -0.00218408])

In [10]:
B = np.random.randn(10)
B

array([-1.62505226,  0.11255443, -0.75230592, -0.21154409,  1.46523717,
       -0.38079047,  0.23484606, -0.46488473,  1.86190627, -0.71942533])

In [11]:
np.add(A,B)

array([-1.13768492,  1.03480927, -0.38743624, -0.88423544,  1.29757032,
       -0.32214788, -0.49908659,  0.79637008,  0.42810384, -0.72160941])

In [12]:
np.maximum(A, B)

array([ 0.48736733,  0.92225484,  0.36486967, -0.21154409,  1.46523717,
        0.05864259,  0.23484606,  1.26125482,  1.86190627, -0.00218408])